Load Posts from Server
valomedia/JetNews pull request #2
Opened 2024-10-06 14:12 UTC by mvlexs

solved issue #1

2024-10-09 14:29 UTC, jp-hoehmann reviewed
Thanks for the PR, your changes look good for the most part :-)

There's three major things that need fixing:
* The app currently crashes when there is no internet connection, instead it should show an error to the user.
* The tests currently fail to build, because BlockingFakePostsRepository doesn't exist, instead the existing tests should still run and none of the tests should fail.
* The previews for a bunch of the Composables are either removed or broken, instead all previews that existed previously should still exist and be usable.

Other than that, there are some minor things I've commented on the individual files.

2024-10-09 14:29 UTC, jp-hoehmann commented on app/build.gradle.kts
> +    implementation(libs.firebase.crashlytics.buildtools)
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/FakePostsRepository.kt
If this is no longer needed, remove this file

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +    private fun shouldRandomlyFail(): Boolean = ++requestCount % 5 == 0
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +import kotlinx.coroutines.delay
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/PostsData.kt
> +import com.example.jetnews.JetnewsApplication
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/PostsData.kt
> +
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/PostsData.kt
> +        @Inject @MinimumBalance lateinit var minimumBalance: BigDecimal
Revert unnecessary whitespace change

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/PostsData.kt
> +            ...
Revert unecessary whitespace change

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/JetnewsApplication.kt
Revert all changes to this file

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/glance/ui/Post.kt
> +}
Revert unnecessary whitespace change

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/model/Post.kt
> +}
Revert unnecessary whitespace change

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
> +//import com.example.jetnews.data.posts.impl.post3
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
> +//import com.example.jetnews.data.posts.impl.post3
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
> -        painter = painterResource(post.imageId),
Remove import for painterResource

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
> -        Image(
Remove unused import for Image

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
> -            painter = painterResource(post.imageId),
Remove unused import for painterResource

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCardYourNetwork.kt
> -            Image(
Remove unused import for Image

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCardYourNetwork.kt
> -                painter = painterResource(post.imageId),
Remove unused import for painterResource

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCardYourNetwork.kt
> -
Revert unnecessary whitespace change

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCardYourNetwork.kt
> -
Revert unnecessary whitespace change

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCards.kt
> +//}
Put these previews back

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCards.kt
> +import androidx.compose.foundation.layout.height
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCards.kt
> +import androidx.compose.ui.layout.ContentScale
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCards.kt
> -        painter = painterResource(post.imageThumbId),
Remove unused import for painterResource

2024-10-09 14:29 UTC, jp-hoehmann commented on gradle/libs.versions.toml
> +firebaseCrashlyticsBuildtools = "3.0.2"
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on gradle/libs.versions.toml
> +firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
Remove this

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
Fix previews

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/home/HomeScreens.kt
Fix previews

2024-10-09 14:29 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
Fix previews

2024-10-09 15:54 UTC, mvlexs commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +import kotlinx.coroutines.delay
Code is depending on imported Modules, therefor it should not be removed

2024-10-20 16:16 UTC, mvlexs commented
applied changes to comply with response to PR-1, except for problem with crashes without internet, still working on an optimal solution

2024-10-28 14:09 UTC, mvlexs commented
fixed: app crashing when no internet connection is available

2024-10-31 22:00 UTC, jp-hoehmann requested changes
Looks good. All working now. I have a few formatting nitpicks, but that's it.

2024-10-31 22:00 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +
Unnecessary whitespace change.

2024-10-31 22:00 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +
Remove extra whitespace

2024-10-31 22:00 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +
Remove extra whitespace

2024-10-31 22:00 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +
Remove extra whitespace.

2024-10-31 22:00 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/PostsData.kt
> +        ...
Unnecessary whitespace change.

2024-10-31 22:03 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +                Log.d("DebugMalik",posts.toString())
Remove this.

2024-10-31 22:03 UTC, jp-hoehmann commented on app/src/main/java/com/example/jetnews/data/posts/impl/HttpPostsRepository.kt
> +                Log.d("ErrorMalik",e.toString())
Remove this.

2024-11-04 13:17 UTC, mvlexs commented
removed unnecessary whitespace changes and logs

2024-12-11 22:37 UTC, merged